//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsTag
    {
        public int IdClientTag { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> IDTag { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TagClient TagClient { get; set; }
    }
}
