//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int IDEmployee { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string SerieNumberPassport { get; set; }
        public string DepartmentCode { get; set; }
        public string Gender { get; set; }
        public string PaymentRatio { get; set; }
        public string Birthday { get; set; }
        public string SpecialistCategory { get; set; }
    }
}
