//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRecord
    {
        public int IDRecord { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public string Comment { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> IDService { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Service Service { get; set; }
    }
}
