//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceGood
    {
        public int IDServiceGood { get; set; }
        public int IDService { get; set; }
        public Nullable<int> IDGood { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Service Service { get; set; }
    }
}
